### ISSUE TITLE
Incompatibility with Java 13?

### ISSUE THREAD

**Issue by scottstouffer** [jibx/jibx#12]
I just updated my Java version to 13 and the build does this:

     [java] Exception in thread "main" java.lang.IllegalStateException: Internal error: unable to find class Set

     [java] 	at org.jibx.custom.classes.ClassCustom.apply(ClassCustom.java:607)

     [java] 	at org.jibx.custom.classes.PackageCustom.apply(PackageCustom.java:147)

     [java] 	at org.jibx.custom.classes.GlobalCustom.fillClasses(GlobalCustom.java:460)

     [java] 	at org.jibx.binding.generator.BindGenCommandLine.applyOverrides(BindGenCommandLine.java:162)

     [java] 	at org.jibx.custom.CustomizationCommandLineBase.processArgs(CustomizationCommandLineBase.java:188)

     [java] 	at org.jibx.binding.generator.BindGen.main(BindGen.java:1298)

**Comment by doncorley** [comment]
This issue has been resolved with the release of JiBX 1.3.3.
Closed.
