### ISSUE TITLE
Unable to use JiBX with Java 8

### ISSUE THREAD

**Issue by manish-in-java** [jibx/jibx#3]
Java: Oracle JDK 1.8.0.0, Oracle JDK 1.8.0.05, OpenJDK 1.8.0
OS: 64-bit CentOS, 64-bit RedHat, 64-bit Amazon Linux, 64-bit Fedora, 64-bit Windows 7 Professional, 64-bit Windows 8 Pro
JiBX: 1.2.5

We are trying to upgrade our applications (around 60 in number) to Java 8.  All of them use JiBX and JiBX Maven plugin version 1.2.5.  The following error is received during the Maven builds and the builds fail:

```
Failed to execute goal org.jibx:jibx-maven-plugin:1.2.5:bind (bind-compile) on project common: Error loading class java.lang.CharSequence: Error reading path java/lang/CharSequence.class for class java.lang.CharSequence
  ...
  at org.jibx.binding.classes.ClassCache$ClassCacheLocator.getClassInfo(ClassCache.java:291)
  at org.jibx.binding.model.ClassHierarchyContext.accumulateInterfaces(ClassHierarchyContext.java:95)
  at org.jibx.binding.model.ClassHierarchyContext.addTypedComponent(ClassHierarchyContext.java:121)
  ...
```

This problem has existed since the first OpenJDK developer preview came out and has been reported in several forums.  What are the plans to fix this?

**Comment by analytically** [comment]
+1

**Comment by zhupan** [comment]
+1

**Comment by markathomas** [comment]
Perhaps JiBX should move to a different bytecode library such as ASM, Byteman, or Byte Buddy. It appears BCEL hasn't seen any activity in quite a while.

**Comment by Vad1mo** [comment]
I am not so sure this could be done that easy. do you have knowledge in one of these tools you are refering? You could give it a try.

**Comment by manish-in-java** [comment]
I made an attempt to port over to ASM, spent 2 days, could not port all the code and therefore gave up.  I estimated that it would take about 6 weeks to complete the port.  I contacted Dennis Sosnosky, the original developer of JiBX and he confirmed that he has no plans of upgrading to Java 8 because his estimate was 8-12 weeks and he could not afford to invest that much effort outside of his regular work hours.  Dennis also mentioned that he had made a proposal on the JiBX users list to sponsor a project for him to port over to ASM but no one showed interest.

My team got convinced last year that there was no surety around JiBX getting ported to Java 8.  So, we branched off our production application, got rid of JiBX and plugged in JAXB in its place.  Then we ran some performance tests against our master branch using JiBX and JDK 7 and the new branch using JAXB and JDK 8.  We did not find any conclusive evidence of a performance difference between the two.  Our most complicated use case involves importing a file containing 36,000+ products with each product having over 200 attributes in the XML file.  We did not find much practical difference between JiBX and JAXB with this file.  Also, all our XML serialization-deserialization use cases are infrequent so there was no real reason to worry too much about performance.  We therefore migrated to JAXB immediately and have not seen any apparent problems so far.

All our XML manipulation code is in a single class that is invoked from multiple places.  Therefore, we had to change only one file and we were done.  For teams using a similar approach, migration to JAXB may be a viable option, given that JAXB is now part of the standard JDK and therefore guaranteed to get upgraded with Java versions.

For those looking for an example, here is our code (comments and some sensitive parts ommitted):

```
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.Serializable;

public class XMLHandler
{
  public static <T extends Serializable> T read(final InputStream stream, final Class<T> type)
  {
    try
    {
      return (T) JAXBContext.newInstance(type).createUnmarshaller().unmarshal(stream);
    }
    catch(final JAXBException e)
    {
      throw new RuntimeException("Unable to read from XML input stream for class " + type.getName() + ".", e);
    }

    return null;
  }

  public static <T extends Serializable> void write(final OutputStream stream, final T object)
  {
    try
    {
      JAXBContext.newInstance(object.getClass()).createMarshaller().marshal(object, stream);
    }
    catch (final JAXBException e)
    {
      throw new RuntimeException("Unable to write to XML output stream for class " + object.getClass().getName() + ".", e);
    }
  }
}
```

**Comment by passyt** [comment]
I have re-code the binding part of Jibx with Javassist, and it support JDK1.8. See my project: https://github.com/passyt/jibx-bind

**Comment by archiecobbs** [comment]
FYI,

JiBX 1.2.6 binding now works on Java 1.8. You have to use the latest 6.0-SNAPSHOT of the BCEL library, which is available [here](https://repository.apache.org/content/groups/snapshots/org/apache/bcel/bcel/6.0-SNAPSHOT/).

However and weirdly, it works for me on Linux, but not on Mac OS X. I'm using OpenJDK 1.8.0_60-b27 on Linux and Oracle Java 1.8.0_60-b27 on Mac OS X. On Mac OS X I'm still getting the `java.lang.CharSequence` error.

**Comment by markathomas** [comment]
check your environment.  if using Ant, please remove any references to
bcel, ant-bcel, and apache-bcel from any files in /etc/ant.d/ (or wherever
those files may be in an OSX environment) as those jars will be added to
ant's bootclasspath and override your classpath

Regards,

Mark Thomas
spatialguru.net@gmail.com
205.529.9013

"Commit to the Lord whatever you do,
    and your plans will succeed." - Proverbs 16:3

**Comment by archiecobbs** [comment]
Thanks! That was indeed the problem. This fixed it:

`$ find /usr/local/Cellar/ant -type f -iname '*bcel*'  | xargs rm`

FYI I'm using `brew` for installing 3rd party software on Mac OS X.

**Comment by markathomas** [comment]
you're welcome

Regards,

Mark Thomas
spatialguru.net@gmail.com
205.529.9013

"Commit to the Lord whatever you do,
    and your plans will succeed." - Proverbs 16:3

**Comment by alberto-hernandez** [comment]
Hi All,

Since past July, BCEL 6.0 is available so I suppose new version could be realease with this dependency.
Thanks for your effort.

**Comment by zhupan** [comment]
It‘s a good news.

**Comment by doncorley** [comment]
JiBX 1.3.0-SNAPSHOT has been released.

Thanks to the new BCEL release, JiBX is now compatible with JDK 1.6, 1.7, and 1.8.

You can find the jar file here:
https://sourceforge.net/projects/jibx/files/jibx/jibx-1.3.0-SNAPSHOT/jibx_1_3_0_SNAPSHOT.zip

The snapshot is in the maven central snapshot repo.

You can browse maven snapshots here:
https://oss.sonatype.org/content/repositories/snapshots/org/jibx/

To use a snapshot in your pom file, add a repository section:
<repositories>
    <repository>
      <id>central</id>
      <name>Maven Repository Switchboard</name>
      <layout>default</layout>
      <url>http://repo1.maven.org/maven2</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>

    <repository>
      <id>central-snapshot</id>
      <name>Central Repository</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <layout>default</layout>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
  </repositories>
 
  <pluginRepositories>
    <pluginRepository>
      <id>central</id>
      <name>Maven Plugin Repository</name>
      <url>http://repo1.maven.org/maven2</url>
      <layout>default</layout>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
    </pluginRepository>

    <pluginRepository>
      <id>central-snapshot</id>
      <name>Central Repository</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <layout>default</layout>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>false</enabled>
      </releases>
    </pluginRepository>
  </pluginRepositories>

Test it. Log your issues here:
https://github.com/jibx -> Issues

It looks pretty solid. I should be able to put out a release in a few weeks.

**Comment by doncorley** [comment]
Fixed!

**Comment by scofier** [comment]
on maven , we should update maven-jibx-plugin  to 1.3.1

<groupId>org.jibx</groupId>
<artifactId>maven-jibx-plugin</artifactId>
<version>1.3.1</version>
